version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html

  certbot:
    image: certbot/certbot
    container_name: certbot_container
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email edward@email.com -d e2ard.com
    depends_on:
      - nginx
